# Generated by Django 4.2.5 on 2023-09-28 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secret_santa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='price_range',
            new_name='price_limit',
        ),
    ]
