# Generated by Django 4.2.5 on 2023-09-28 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secret_santa', '0002_rename_price_range_group_price_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='draw_date',
        ),
    ]
