# Generated by Django 4.2.5 on 2023-09-28 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secret_santa', '0004_participant_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='creator',
        ),
    ]
