# Generated by Django 4.2.5 on 2023-09-28 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secret_santa', '0006_participant_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
    ]
