# Generated by Django 4.2.5 on 2023-09-28 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secret_santa', '0008_group_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='event',
        ),
    ]
