# Generated by Django 4.2.5 on 2023-10-02 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secret_santa', '0010_group_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='exchange_date',
        ),
    ]
