# Generated by Django 4.2.5 on 2023-10-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_santa', '0011_remove_group_exchange_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftpair',
            name='date',
            field=models.DateField(default='2023-12-31'),
        ),
    ]
