# Generated by Django 4.2.5 on 2023-10-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_santa', '0012_giftpair_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftpair',
            name='date',
            field=models.DateField(),
        ),
    ]
