# Generated by Django 4.2.5 on 2023-10-06 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secret_santa', '0013_alter_giftpair_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gift',
        ),
    ]
