# Generated by Django 4.2.5 on 2023-10-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_santa', '0014_delete_gift'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftpair',
            name='game_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='group',
            name='price_limit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
